# NumPy

## Install and Import NumPy

In [5]:
!pip install numpy

In [3]:
import numpy as np

In [6]:
def pythonsum(n):
    a = b = list(range(n))
    c = []
    for i in range(len(a)):
        x = a[i] ** 2
        y = b[i] ** 3
        c.append(x + y)
    return c

c = pythonsum(10)
print(c)

[0, 2, 12, 36, 80, 150, 252, 392, 576, 810]


In [4]:
def numpysum(n):
    a = np.arange(n) ** 2 
    b = np.arange(n) ** 3 
    c=a+ b
    return c

x = numpysum(10) 
print(x)

[  0   2  12  36  80 150 252 392 576 810]


In [7]:
## membandingkan kecepatan antara numpy dg List core python 
from datetime import datetime
size = 100
start = datetime.now()
c = pythonsum(size)
delta = datetime.now() - start
print("The last 2 elements of the sum", c[-2:])
print("PythonSum elapsed time in microseconds", delta.microseconds)

The last 2 elements of the sum [950796, 980100]
PythonSum elapsed time in microseconds 0


In [8]:
start = datetime.now()
c = numpysum(size)
delta = datetime.now() - start
print("The last 2 elements of the sum", c[-2:])
print("NumPySum elapsed time in microseconds", delta.microseconds)

The last 2 elements of the sum [950796 980100]
NumPySum elapsed time in microseconds 0


# Array

In [7]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(a[0])

[1 2 3 4]


**Creating Array**

In [ ]:
np.array()
np.zeros()
np.ones()
np.empty()
np.arange()

In [100]:
import numpy as np

a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [ ]:
array([1, 2, 3])

In [99]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [98]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [97]:
np.empty(6)

array([0.51136678, 0.60831278, 0.29045633, 0.31968898, 0.65017905,
       0.17718432])

In [10]:
print(np.arange(4))
print(np.arange(0, 10, 2))

[0 1 2 3]
[0 2 4 6 8]


In [1]:
arange([start], stop, [step])

np.arange(0, 10, 2)
#list np mulai dari 0 hingga 10 tetapi jangan sertakan 10 dan
#buat angka tsb melakukan kenaikan 2 setiap kali

NameError: name 'arange' is not defined

In [86]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [84]:
np.arange(2, 29, 5)

array([ 2,  7, 12, 17, 22, 27])

**Add, Remove, and Sort**

In [11]:
np.append()
np.delete()
np.sort()

TypeError: _append_dispatcher() missing 2 required positional arguments: 'arr' and 'values'

In [12]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [13]:
np.append(arr, [1,2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [15]:
np.delete(arr, 1)

array([1, 3, 4, 5, 6, 7, 8])

In [16]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

## Sorting Array

 np.sort?  ## Signature: np.sort(a, axis=-1, kind=None, order=None)

 ----------------------------------
|   kind    |  speed  |    stable |
|:--------|:-------|:--------| 
|'quicksort' |   1    |          no |
|'heapsort'  |   3   |          no |
|'mergesort' |   2   |       yes |
|'timsort'   |   2  |          yes |

In [9]:
data = np.array([[4, 1, 0, 5],[1, 5, 3, 4]])
data

array([[4, 1, 0, 5],
       [1, 5, 3, 4]])

In [10]:
# menambahkan parameter axis =1 
data.sort(axis=1)
print(data)

[[0 1 4 5]
 [1 3 4 5]]


In [ ]:
## dengan kita menambahkan parameter "axis=0" kita menghasilkan 
## array baru yang merupakan hasil sorting berdasarkan per kolom 

In [11]:
data = np.array([[4, 1, 0, 5],[1, 5, 3, 4]])
# menambahkan parameter axis =0 
print(data)
print("sebelum di sort axis=0")
print(10*"=====")
data.sort(axis=0)
print(data)

[[4 1 0 5]
 [1 5 3 4]]
sebelum di sort axis=0
[[1 1 0 4]
 [4 5 3 5]]


In [12]:
#### sorting dengan membuat structure array
dtype = [('name', 'S10'), ('height', float), ('age', int)]  ##  name type string , heigh type float , age type int
values = [('Arthur', 1.8, 41), 
          ('Lancelot', 1.9, 38),
          ('Galahad', 1.7, 38)]
a = np.array(values, dtype=dtype) # create a structured array
print(a)

[(b'Arthur', 1.8, 41) (b'Lancelot', 1.9, 38) (b'Galahad', 1.7, 38)]


In [13]:
x = np.sort(a, order='name')  
print(x)

[(b'Arthur', 1.8, 41) (b'Galahad', 1.7, 38) (b'Lancelot', 1.9, 38)]


In [14]:
np.sort(a, order=['age', 'height'])   

array([(b'Galahad', 1.7, 38), (b'Lancelot', 1.9, 38),
       (b'Arthur', 1.8, 41)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i4')])

In [15]:
values[1] # menghasilkan tuple 

('Lancelot', 1.9, 38)

In [16]:
values[0][0] ## arthur

'Arthur'

**Shape and Size**

In [ ]:
ndarray.ndim #memberi tahu jumlah axes, atau dimensi, dari array
ndarray.size #memberi tahu jumlah total elemen array
ndarray.shape #menampilkan tuple integer yang menunjukkan jumlah elemen yang disimpan disepanjang setiap dimensi array

In [19]:
array_example = np.array([[[0, 1, 2, 3],
                          [4, 5, 6, 7]],
                         
                        [[0, 1, 2, 3],
                        [4, 5, 6, 7]],
                        
                        [[0, 1, 2, 3],
                        [4, 5, 6, 7]]])

print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [20]:
array_example.ndim

3

In [21]:
array_example.size

24

In [22]:
array_example.shape

(3, 2, 4)

In [23]:
arr_one = np.array([[1, 2, 3, 4, 5]])

In [24]:
arr_one.ndim

2

In [25]:
arr_one.size

5

**Reshape**

In [28]:
import numpy as np

In [ ]:
np.reshape()
#memberikan bentuk baru ke array tanpa mengubah datanya

In [30]:
a = np.arange(6)

print(a)

[0 1 2 3 4 5]


In [31]:
#reshape the array to an array with 3 rows and 2 columns

b = a.reshape(3,2)

print(b)

[[0 1]
 [2 3]
 [4 5]]


In [32]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [ ]:
numpy.reshape(a, newshape, order)

# a = array yang akan di-reshaped
# newshape = bentuk baru yang diinginkan
# order : 'C' means to read/write the elements using C-like index order
# 'F' means to read/write the elements using fortran-like index order
# 'A' means to read/write the elements in Fortran-like index order 
# if a is Fortran contiguous in memory, C-like order otherwise (optional parameter)

**Convert 1D to 2D**

In [ ]:
np.newaxis
np.expand_dims

#untuk meningkatkan dimensi array yang sudah ada

In [33]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [34]:
#use np.newaxis to add a new axis

a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [35]:
#convert a 1D array to a row vector by inserting an axis along the first dimension

row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [36]:
#for a column vector, you can insert an axis along the second dimension

col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [37]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [38]:
#use np.expand_dims to add an axis at index position 1 with:

b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [39]:
#you can add an axis at index position 0 with:

c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

# Indexing and Slicing

In [40]:
data = np.array([1,2,3])

print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

[1 2 3]
1
2
[1 2]
[2 3]
[2 3]


**mengambil bagian dari array atau elemen array tertentu**

In [41]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [42]:
print(a[a<5])

[1 2 3 4]


In [43]:
five_up = (a >= 5)

print(a[five_up])
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]
[ 5  6  7  8  9 10 11 12]


In [44]:
divisible_by_2 = a[a%2==0]

print(divisible_by_2)

[ 2  4  6  8 10 12]


In [45]:
c = a[(a > 2) & (a < 11)]

print(c)

[ 3  4  5  6  7  8  9 10]


# Creating Array from Existing Data

In [ ]:
slicing indexing
np.vstack()
np.hstack()
np.hsplit()
.view()
.copy()

In [46]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [47]:
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

**menumpuk dua array yang ada**

In [48]:
a_1 = np.array([[1, 1],
                [2, 2]])

In [49]:
a_2 = np.array([[3, 3],
               [4, 4]])

In [52]:
np.vstack((a_1, a_2)) #vertically

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [55]:
np.hstack((a_1, a_2)) #horizontally

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

**membagi sebuah array menjadi beberapa array yang lebih kecil**

In [56]:
arrsplit = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                    [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])
print(arrsplit)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [57]:
#split this array into 3 equally shaped arrays

np.hsplit(arrsplit, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

**membuat objek baru yang terlihat sama dengan array asli (shallow copy)**

In [58]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [59]:
#create new array object that looks at the same data

b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [60]:
#make a complete copy of the array and its data (a deep copy)

c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# Basic Array Operations

In [ ]:
data - ones
data * data
data / data

In [61]:
a = np.array([1, 2, 3, 4])
a.sum() #add all of the elements in the array

10

In [62]:
b = np.array([[1, 1], [2, 2]])
b

array([[1, 1],
       [2, 2]])

In [63]:
#sum the rows

b.sum(axis = 0)

array([3, 3])

In [64]:
#sum the columns

b.sum(axis = 1)

array([2, 4])

In [66]:
data = np.array([1, 2])
data

array([1, 2])

In [67]:
ones = np.ones(2)
ones

array([1., 1.])

In [70]:
data * data

array([1, 4])

In [71]:
data / data

array([1., 1.])

# Broadcasting

Mekanisme yang memungkinkan NumPy melakukan operasi pada array dengan bentuk berbeda. Dimensi array harus kompatibel, misalnya jika dimensi kedua array sama atau salah satunya adalah 1. Jika tidak kompatibel maka akan error.

In [72]:
data * 2

array([2, 4])

**More Array Operations**

Maximum, minimum, sum, mean, product, standard deviation, and more

In [ ]:
data.max()
data.min()
data.sum()

In [23]:
A = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
             [0.54627315, 0.05093587, 0.40067661, 0.55645993],
             [0.12697628, 0.82485143, 0.26590556, 0.56917101]])
print(A)

[[0.45053314 0.17296777 0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645993]
 [0.12697628 0.82485143 0.26590556 0.56917101]]


In [77]:
A.sum()

4.8595784

In [78]:
A.min()

0.05093587

In [79]:
A.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [80]:
A.max()

0.82485143

In [81]:
A.std()

0.21392120766089617

In [24]:
print(A.argmin()) ## posisi index 

5


In [26]:
print(A.argmax()) ## posisi index 

9


### Function

Beberapa fungsi utilitas dasar dari modul np.random adalah np.random.seed dan np.random.shuffle. Kami menggunakan fungsi np.random.seed untuk mengatur random seed, yang memungkinkan kami untuk mengontrol output dari fungsi pseudo-random. Fungsi mengambil satu bilangan bulat sebagai argumen, yang mewakili random seed.

Kode di bawah ini menggunakan np.random.seed dengan seed acak yang sama. 
Perhatikan bagaimana output dari fungsi random di setiap proses berikutnya adalah identik ketika 
kita menetapkan random seed yang sama.

In [17]:
np.random.seed(0)
print(np.random.randint(10))

5


In [18]:
random_arr = np.random.randint(10,100,6) # dari 10 ke 100 sebanyak 6 
print(random_arr)

[74 77 77 19 93 31]


In [19]:
np.random.seed(0)
random_arr = np.random.randint(3, high=100,
                               size=(2, 2)) ## randint(low, high=None, size=None, dtype=int)

print(repr(random_arr))

array([[47, 50],
       [67, 70]])


In [20]:
# New seed
np.random.seed(2)

random_arr = np.random.randint(3, high=100,
                               size=(2, 2))
print(repr(random_arr))

array([[43, 18],
       [75, 25]])


In [21]:
# Original seed
np.random.seed(0)
random_arr = np.random.randint(3, high=100,
                               size=(2, 2))
print(repr(random_arr))

array([[47, 50],
       [67, 70]])


## Save Array into file

In [27]:
A = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

print(A)

[[0.45053314 0.17296777 0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645993]
 [0.12697628 0.82485143 0.26590556 0.56917101]]


In [28]:
np.save("myarray2.npy",A)

In [29]:
responseFile = np.load('myarray2.npy')
print(responseFile)

[[0.45053314 0.17296777 0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645993]
 [0.12697628 0.82485143 0.26590556 0.56917101]]


# Latihan 

* Buat lah Array 
```
[[  0  72   3]
 [  1   3 -60]
 [ -3  -2   4]]
``` 

Simpan file Array tersebut 
Kemudian lakukan load file Array 

lakukan pencarian data dibawah ini 

Temukan Nilai minum dan maksimum pada file tersebut 

Temukan Nilai minum di setiap kolom 
Temukan Nilai Maksimum di setiap Kolom 
Menemukan Nilai Minimum di setiap baris 
Menemukan Nilai Maksimum di setiap baris 

In [30]:
arr = np.array([[0, 72, 3],
                [1, 3, -60],
                [-3, -2, 4]])
print(arr)

[[  0  72   3]
 [  1   3 -60]
 [ -3  -2   4]]


In [31]:
np.save("myarray3.npy",arr)

In [32]:
resfile = np.load('myarray3.npy')
print(resfile)

[[  0  72   3]
 [  1   3 -60]
 [ -3  -2   4]]


In [33]:
print(resfile.min())
print(resfile.max())

print(repr(resfile.min(axis=0)))
print(repr(resfile.max(axis=0)))

print(repr(resfile.max(axis=-1)))
print(repr(resfile.min(axis=-1)))


-60
72
array([ -3,  -2, -60])
array([ 1, 72,  4])
array([72,  3,  4])
array([  0, -60,  -3])


# Matrices

**Creating Matrices**

In [73]:
np.ones((3,2))
np.zeros((3,2))
np.random.random((3,2))

array([[0.57950009, 0.67372016],
       [0.47120735, 0.37126141],
       [0.55133344, 0.42473377]])

In [74]:
print(np.ones((3,2)))
print(np.zeros((3,2)))
print(np.random.random((3,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.51136678 0.60831278]
 [0.29045633 0.31968898]
 [0.65017905 0.17718432]]


# Matrix Arithmetic

dapat menjumlahkan dan mengalikan matriks menggunakan operator aritmatika jika kedua matriks berukuran sama

In [141]:
data = np.array([[1, 2], [3, 4]])
print(data)

[[1 2]
 [3 4]]


In [142]:
ones = np.ones([2, 2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [143]:
print(data + ones)

[[2. 3.]
 [4. 5.]]


In [144]:
ones_row = np.ones([1, 2])
print(ones_row)

[[1. 1.]]


In [145]:
print(data + ones_row)

[[2. 3.]
 [4. 5.]]


# Dot Product

Perbedaan utama yang harus dibuat dengan aritmatika adalah kasus perkalian matriks menggunakan produk titik. NumPy memberikan setiap matriks metode dot() yang dapat kita gunakan untuk melakukan operasi produk dot dengan matriks lain

In [46]:
np.dot(3, 4)

12

In [47]:
a = np.arange(3*4*5*6).reshape((3,4,5,6)) 
print(a)

[[[[  0   1   2   3   4   5]
   [  6   7   8   9  10  11]
   [ 12  13  14  15  16  17]
   [ 18  19  20  21  22  23]
   [ 24  25  26  27  28  29]]

  [[ 30  31  32  33  34  35]
   [ 36  37  38  39  40  41]
   [ 42  43  44  45  46  47]
   [ 48  49  50  51  52  53]
   [ 54  55  56  57  58  59]]

  [[ 60  61  62  63  64  65]
   [ 66  67  68  69  70  71]
   [ 72  73  74  75  76  77]
   [ 78  79  80  81  82  83]
   [ 84  85  86  87  88  89]]

  [[ 90  91  92  93  94  95]
   [ 96  97  98  99 100 101]
   [102 103 104 105 106 107]
   [108 109 110 111 112 113]
   [114 115 116 117 118 119]]]


 [[[120 121 122 123 124 125]
   [126 127 128 129 130 131]
   [132 133 134 135 136 137]
   [138 139 140 141 142 143]
   [144 145 146 147 148 149]]

  [[150 151 152 153 154 155]
   [156 157 158 159 160 161]
   [162 163 164 165 166 167]
   [168 169 170 171 172 173]
   [174 175 176 177 178 179]]

  [[180 181 182 183 184 185]
   [186 187 188 189 190 191]
   [192 193 194 195 196 197]
   [198 199 200 201 202 203]


In [48]:
b = np.arange(3*4*5*6)[::-1].reshape((5,4,6,3))
print(b)

[[[[359 358 357]
   [356 355 354]
   [353 352 351]
   [350 349 348]
   [347 346 345]
   [344 343 342]]

  [[341 340 339]
   [338 337 336]
   [335 334 333]
   [332 331 330]
   [329 328 327]
   [326 325 324]]

  [[323 322 321]
   [320 319 318]
   [317 316 315]
   [314 313 312]
   [311 310 309]
   [308 307 306]]

  [[305 304 303]
   [302 301 300]
   [299 298 297]
   [296 295 294]
   [293 292 291]
   [290 289 288]]]


 [[[287 286 285]
   [284 283 282]
   [281 280 279]
   [278 277 276]
   [275 274 273]
   [272 271 270]]

  [[269 268 267]
   [266 265 264]
   [263 262 261]
   [260 259 258]
   [257 256 255]
   [254 253 252]]

  [[251 250 249]
   [248 247 246]
   [245 244 243]
   [242 241 240]
   [239 238 237]
   [236 235 234]]

  [[233 232 231]
   [230 229 228]
   [227 226 225]
   [224 223 222]
   [221 220 219]
   [218 217 216]]]


 [[[215 214 213]
   [212 211 210]
   [209 208 207]
   [206 205 204]
   [203 202 201]
   [200 199 198]]

  [[197 196 195]
   [194 193 192]
   [191 190 189]
   [188 1

In [49]:
np.dot(a, b)[2,3,2,1,2,2]

499128

In [50]:
sum(a[2,3,2,:] * b[1,2,:,2])

499128

In [138]:
a_1 = np.array([[1, 2, 3], [4, 5, 6]])
print(a_1)
print(a_1.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [139]:
a_2 = np.array([[7, 8], [9, 10], [11, 12]])
print(a_2)
print(a_2.shape)

[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [140]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

### Matrix Indexing
Operasi pengindeksan dan pemotongan menjadi lebih berguna saat kita memanipulasi matriks
    
    
   ```np.array([[1, 2], [3, 4], [5, 6]])```

    
<img src="https://i.ibb.co/4sS8HGD/Screen-Shot-2021-09-02-at-8-26-34-AM.png" align="left"> 

In [51]:
data = np.array([[1, 2], [3, 4], [5, 6]])

print(data)

[[1 2]
 [3 4]
 [5 6]]


In [52]:
print(data[0,1])

2


In [53]:
print(data[1:3])

[[3 4]
 [5 6]]


In [54]:
print(data[0:2,0])

[1 3]


In [55]:
print((data[:]))

[[1 2]
 [3 4]
 [5 6]]


In [56]:
print(data[:, -1]) # -1 kanan
xdata = data[:, -1]
xdata.ndim  # 1 dimensi
##xdata.shape

[2 4 6]


1

In [57]:
print(data[:, 1:]) # -1 kanan
xdata = data[:, 1:]
xdata.ndim  # 2 dimensi
#xdata.shape

[[2]
 [4]
 [6]]


2

In [58]:
print(data[:, :]) 

[[1 2]
 [3 4]
 [5 6]]


In [59]:
print(data[:, 0:1]) 

[[1]
 [3]
 [5]]


In [60]:
print(data[:, 1:2]) 

[[2]
 [4]
 [6]]


In [61]:
print(data[:, 1:]) 

[[2]
 [4]
 [6]]


In [62]:
print((data[0:2,:]))

[[1 2]
 [3 4]]


# Latihan Studi Kasus

10 buah botol minum akan dibuat untuk menyimpan air dengan jari2 dan tinggi yang berbeda - beda . 
Besaran jari2 dan tinggi botol adalah bilang bulat kisaran 7 sampai dengan 20 cm . 

Temukan : 

1. Volume air yang dapat disimpan di setiap botol 
2. Total volume air yang tersimpan dalam semua botol 
3. Botol mana yang volume air terkecil dan temukan volumenya 
4. Botol mana yang menampung volume air terbesar dan temukan volume airnya . 
5. Rata-rata volume yang dapat di tampung di tiap botol 

Solusi : 
1. Lakukan generate tinggi botol dan jari2 
2. Punya batasan 7 sampai 20 , kemudian sebanyak 10 
   Dengan kata lain harus mengenerate sebanyak 20 
3. Membentuk botol sebanyak 10 buah (tinggi dan jari2) 
4. Setelah terbentuk botol mencari volume air masing botol 
   Volume air = (Pi x r^2 x t ) untuk numpy pi = np.pi 
5. Mencari Total volume air dalam semua botol sum 
6. Mencari botol yang terkcil dan temukan volume nya 
7. Mencari botol yang terbesar dan temukan volume nya 
8. Mencari rata2 dengan mean 

In [112]:
import numpy as np

In [37]:
np.random.seed(0)
dataBotol = np.random.randint(7,20,20)
print(dataBotol)

[19 12  7 10 18 10 14 16 10 12  9 11 14 13 15 15 19 17  8 13]


In [38]:
dataBotol.resize(10,2)
dataBotol

array([[19, 12],
       [ 7, 10],
       [18, 10],
       [14, 16],
       [10, 12],
       [ 9, 11],
       [14, 13],
       [15, 15],
       [19, 17],
       [ 8, 13]])

In [39]:
#tinggi kolom = 0
#jari kolom = 1
v = np.pi * (dataBotol[:,1] ** 2) * dataBotol[:,0]
v

array([ 8595.39750022,  2199.11485751,  5654.86677646, 11259.46807047,
        4523.89342117,  3421.19439976,  7433.00821839, 10602.87520587,
       17250.48526086,  4247.43326765])

In [40]:
totalVolume = v.sum()
print(f"Total volume  : {totalVolume} ")

Total volume  : 75187.73697836453 


In [42]:
v.argmin()
v[v.argmin()]

2199.1148575128555

In [43]:
v.argmax()
v[v.argmax()]

17250.485260861555

In [45]:
idxBotolKecil = v.argmin()
volumeBotolKecil = v[idxBotolKecil]
print(f"Botol Terkecil Pada Botol index : {idxBotolKecil} volume {volumeBotolKecil}")
idxBotolBesar = v.argmax()
volumeBotolBesar = v[idxBotolBesar]
print(f"Botol Terkecil Pada Botol index : {idxBotolBesar} volume {volumeBotolBesar}")

Botol Terkecil Pada Botol index : 1 volume 2199.1148575128555
Botol Terkecil Pada Botol index : 8 volume 17250.485260861555


# Latihan Index

In [63]:
import numpy as np

In [64]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print((arr[:]))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [65]:
print((arr[1:]))

[[4 5 6]
 [7 8 9]]


In [66]:
print(repr(arr[:, -1]))

array([3, 6, 9])


In [67]:
print(repr(arr[:, 1:]))

array([[2, 3],
       [5, 6],
       [8, 9]])


In [68]:
print(repr(arr[0:1,:]))

array([[1, 2, 3]])


In [69]:
print(repr(arr[0:1,:]))

array([[1, 2, 3]])


In [70]:
print(repr(arr[0:2,:]))

array([[1, 2, 3],
       [4, 5, 6]])


In [71]:
print(repr(arr[0:2, 1:]))

array([[2, 3],
       [5, 6]])


In [72]:
print(repr(arr[0, 1:]))

array([2, 3])


### Matrix Aggregation
Kita dapat menjumlahkan matriks dengan cara yang sama seperti kita menjumlahkan vector

In [73]:
data = np.array([[1, 2], [3, 4], [5, 6]])

print(data)

[[1 2]
 [3 4]
 [5 6]]


In [74]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [75]:
print(data.max(axis=0))
print(data.max(axis=1))

[5 6]
[2 4 6]


### Transposing and Reshaping
mentraspose suatu array adalah proses mengubah posisi **element2 vektor baris menjadi vektor kolom demikian pula sebaliknya.* 

Menggunakan numpy , melakukan traspose suatu array dapat dilakukan : 
 dengan cara memangil function **transpose()** atau memanggil properti **T** dari suatu array  

In [76]:
data = np.array([[1, 2], [3, 4], [5, 6]])
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [77]:
print(data.transpose())

[[1 3 5]
 [2 4 6]]


In [78]:
print(data.T)

[[1 3 5]
 [2 4 6]]


In [79]:
data = np.array([[1, 2], [3, 4], [5, 6]])
print(data)
data = data.transpose()
print(data)

[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


Dalam kasus penggunaan yang lebih lanjut, Anda mungkin perlu mengganti dimensi matriks tertentu. 
    Ini sering terjadi dalam aplikasi pembelajaran mesin di mana model tertentu mengharapkan bentuk tertentu untuk input yang berbeda dari kumpulan data Anda.

Metode reshape() NumPy berguna dalam kasus ini. 
Anda hanya memberikan dimensi baru yang Anda inginkan untuk matriks. 
Anda dapat meneruskan -1 untuk suatu dimensi dan NumPy dapat menyimpulkan dimensi yang benar berdasarkan matriks Anda

In [81]:
data_col = np.array([[1, 2, 3, 4, 5, 6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [82]:
data_col.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [83]:
data_col.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

Anda juga dapat menggunakan np.transpose untuk membalikkan atau mengubah sumbu array sesuai dengan nilai yang Anda tentukan. Jika Anda mulai dengan array ini

In [84]:
arr = np.arange(6).reshape((2, 3))
print(arr)

[[0 1 2]
 [3 4 5]]


## Flatten N-Dimensional Array
Ada dua cara populer untuk meratakan array: .flatten() dan .ravel(). Perbedaan utama antara keduanya adalah bahwa array baru yang dibuat menggunakan ravel() sebenarnya adalah referensi ke array induk. Ini berarti bahwa setiap perubahan pada array baru akan mempengaruhi array induk juga. Karena ravel tidak membuat salinan, ini hemat memori.

In [85]:
arrflat = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(arrflat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [86]:
# You can use flatten to flatten your array into a 1D array.
arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])